### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by KoolPal** [actual-saurabh/WooCommerce-Email-Cart#1]
Hi,

Is this plugin abandoned? Can this plugin enable Admin to create a cart and share with the customer?

Thanks

**Comment by actual-saurabh** [comment]
this was built as a demo for a job, not for public consumption. Will archive in a day or so.

**Comment by KoolPal** [comment]
That's a pity. Please see if you can update and share for benefit of all. Thanks
